### ISSUE TITLE
camelToSnakeCase issue

### ISSUE THREAD

**Issue by enheit** [alexnm/json-style-converter#1]
For instance, we have a key fooBar1 in camel case, but if we convert it to snakeCase it represents as foo_bar1 instead of foo_bar_1.

**Comment by alexnm** [comment]
hmm, this is debatable, maybe it should be an option to the functions to consider digits as upper case or lower case

**Comment by enheit** [comment]
Yes, i think it must be optional.

**Comment by enheit** [comment]
Should i wait for the fix? If yes, how long it takes?
Because i use it as JSON response converter and it is a bit terrible to handle response on your own.
Thank you :)

**Comment by alexnm** [comment]
@enheit sorry I'm currently in a longer vacation, feel free to make a PR and I'll see when I catch a few minutes to merge

**Comment by enheit** [comment]
I've added pull request with changes. Please, review. https://github.com/alexnm/json-style-converter/pull/3

**Comment by alexnm** [comment]
solved with https://github.com/alexnm/json-style-converter/commit/b1dcb09170b3ac61c3328b861081dab259777d76
